# Generated by Django 5.1.4 on 2024-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('path', models.CharField(max_length=1024, verbose_name='Путь')),
                ('extension', models.CharField(blank=True, max_length=50, null=True, verbose_name='Расширение')),
                ('modification_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Размер (байт)')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц/параграфов')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('bitrate', models.IntegerField(blank=True, null=True, verbose_name='Битрейт')),
                ('dpi', models.CharField(blank=True, max_length=50, null=True, verbose_name='DPI')),
                ('metadata', models.TextField(blank=True, null=True, verbose_name='Метаданные')),
                ('page_format', models.CharField(blank=True, max_length=50, null=True, verbose_name='Формат страниц')),
            ],
        ),
    ]
